# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmsgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1600, 1536)
        font = QtGui.QFont()
        font.setPointSize(24)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelState = QtGui.QLabel(self.centralwidget)
        self.labelState.setStyleSheet(_fromUtf8("border-width: 2px;\n"
"background-color: rgb(170, 255, 255);\n"
"border-radius: 15px;\n"
"padding: 4px;"))
        self.labelState.setObjectName(_fromUtf8("labelState"))
        self.horizontalLayout.addWidget(self.labelState)
        self.pushButtonLog = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonLog.setFont(font)
        self.pushButtonLog.setStyleSheet(_fromUtf8("border-width: 2px;\n"
"border-radius: 15px;\n"
"padding: 4px;\n"
"background-color: rgb(255, 255, 127);"))
        self.pushButtonLog.setObjectName(_fromUtf8("pushButtonLog"))
        self.horizontalLayout.addWidget(self.pushButtonLog)
        self.pushButtonDel = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonDel.setFont(font)
        self.pushButtonDel.setStyleSheet(_fromUtf8("border-width: 2px;\n"
"background-color: rgb(255, 127, 127);\n"
"border-radius: 15px;\n"
"padding: 4px;"))
        self.pushButtonDel.setObjectName(_fromUtf8("pushButtonDel"))
        self.horizontalLayout.addWidget(self.pushButtonDel)
        self.pushButtonLive = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonLive.setFont(font)
        self.pushButtonLive.setStyleSheet(_fromUtf8("border-width: 2px;\n"
"border-radius: 15px;\n"
"padding: 4px;\n"
"background-color: rgb(170, 255, 127);"))
        self.pushButtonLive.setObjectName(_fromUtf8("pushButtonLive"))
        self.horizontalLayout.addWidget(self.pushButtonLive)
        self.pushButtonStop = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonStop.setFont(font)
        self.pushButtonStop.setStyleSheet(_fromUtf8("border-width: 2px;\n"
"border-radius: 15px;\n"
"padding: 4px;\n"
"background-color: rgb(255, 127, 127);"))
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.horizontalLayout.addWidget(self.pushButtonStop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabLive = QtGui.QWidget()
        self.tabLive.setObjectName(_fromUtf8("tabLive"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabLive)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelCell = QtGui.QLabel(self.tabLive)
        self.labelCell.setStyleSheet(_fromUtf8(""))
        self.labelCell.setObjectName(_fromUtf8("labelCell"))
        self.verticalLayout_4.addWidget(self.labelCell)
        self.tableCell = QtGui.QTableView(self.tabLive)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tableCell.setFont(font)
        self.tableCell.setStyleSheet(_fromUtf8(""))
        self.tableCell.setObjectName(_fromUtf8("tableCell"))
        self.verticalLayout_4.addWidget(self.tableCell)
        self.labelTemp = QtGui.QLabel(self.tabLive)
        self.labelTemp.setStyleSheet(_fromUtf8(""))
        self.labelTemp.setObjectName(_fromUtf8("labelTemp"))
        self.verticalLayout_4.addWidget(self.labelTemp)
        self.tableTemp = QtGui.QTableView(self.tabLive)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tableTemp.setFont(font)
        self.tableTemp.setStyleSheet(_fromUtf8(""))
        self.tableTemp.setObjectName(_fromUtf8("tableTemp"))
        self.verticalLayout_4.addWidget(self.tableTemp)
        self.labelMod = QtGui.QLabel(self.tabLive)
        self.labelMod.setStyleSheet(_fromUtf8(""))
        self.labelMod.setObjectName(_fromUtf8("labelMod"))
        self.verticalLayout_4.addWidget(self.labelMod)
        self.tableMod = QtGui.QTableView(self.tabLive)
        self.tableMod.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tableMod.setFont(font)
        self.tableMod.setStyleSheet(_fromUtf8(""))
        self.tableMod.setObjectName(_fromUtf8("tableMod"))
        self.verticalLayout_4.addWidget(self.tableMod)
        self.tabWidget.addTab(self.tabLive, _fromUtf8(""))
        self.tabCellinfo = QtGui.QWidget()
        self.tabCellinfo.setObjectName(_fromUtf8("tabCellinfo"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabCellinfo)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.labelOcv = QtGui.QLabel(self.tabCellinfo)
        self.labelOcv.setObjectName(_fromUtf8("labelOcv"))
        self.verticalLayout_10.addWidget(self.labelOcv)
        self.tableOcv = QtGui.QTableView(self.tabCellinfo)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tableOcv.setFont(font)
        self.tableOcv.setObjectName(_fromUtf8("tableOcv"))
        self.verticalLayout_10.addWidget(self.tableOcv)
        self.labelOhm = QtGui.QLabel(self.tabCellinfo)
        self.labelOhm.setObjectName(_fromUtf8("labelOhm"))
        self.verticalLayout_10.addWidget(self.labelOhm)
        self.tableOhm = QtGui.QTableView(self.tabCellinfo)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tableOhm.setFont(font)
        self.tableOhm.setObjectName(_fromUtf8("tableOhm"))
        self.verticalLayout_10.addWidget(self.tableOhm)
        self.tabWidget.addTab(self.tabCellinfo, _fromUtf8(""))
        self.tabCAN = QtGui.QWidget()
        self.tabCAN.setObjectName(_fromUtf8("tabCAN"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabCAN)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.labelCAN = QtGui.QLabel(self.tabCAN)
        self.labelCAN.setStyleSheet(_fromUtf8(""))
        self.labelCAN.setObjectName(_fromUtf8("labelCAN"))
        self.verticalLayout_7.addWidget(self.labelCAN)
        self.tableCAN = QtGui.QTableView(self.tabCAN)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tableCAN.setFont(font)
        self.tableCAN.setStyleSheet(_fromUtf8(""))
        self.tableCAN.setObjectName(_fromUtf8("tableCAN"))
        self.verticalLayout_7.addWidget(self.tableCAN)
        self.tabWidget.addTab(self.tabCAN, _fromUtf8(""))
        self.tabParam = QtGui.QWidget()
        self.tabParam.setObjectName(_fromUtf8("tabParam"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabParam)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxCellVolt = QtGui.QCheckBox(self.tabParam)
        self.checkBoxCellVolt.setObjectName(_fromUtf8("checkBoxCellVolt"))
        self.verticalLayout_3.addWidget(self.checkBoxCellVolt)
        self.checkBoxCellTemp = QtGui.QCheckBox(self.tabParam)
        self.checkBoxCellTemp.setObjectName(_fromUtf8("checkBoxCellTemp"))
        self.verticalLayout_3.addWidget(self.checkBoxCellTemp)
        self.checkBoxPackVol = QtGui.QCheckBox(self.tabParam)
        self.checkBoxPackVol.setObjectName(_fromUtf8("checkBoxPackVol"))
        self.verticalLayout_3.addWidget(self.checkBoxPackVol)
        self.checkBoxPackCur = QtGui.QCheckBox(self.tabParam)
        self.checkBoxPackCur.setObjectName(_fromUtf8("checkBoxPackCur"))
        self.verticalLayout_3.addWidget(self.checkBoxPackCur)
        self.checkBoxMod = QtGui.QCheckBox(self.tabParam)
        self.checkBoxMod.setObjectName(_fromUtf8("checkBoxMod"))
        self.verticalLayout_3.addWidget(self.checkBoxMod)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelTEMP_HIGH_LIMIT = QtGui.QLabel(self.tabParam)
        self.labelTEMP_HIGH_LIMIT.setObjectName(_fromUtf8("labelTEMP_HIGH_LIMIT"))
        self.horizontalLayout_3.addWidget(self.labelTEMP_HIGH_LIMIT)
        self.lineEditTEMP_HIGH_LIMIT = QtGui.QLineEdit(self.tabParam)
        self.lineEditTEMP_HIGH_LIMIT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTEMP_HIGH_LIMIT.setObjectName(_fromUtf8("lineEditTEMP_HIGH_LIMIT"))
        self.horizontalLayout_3.addWidget(self.lineEditTEMP_HIGH_LIMIT)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.TEMP_LOW_LIMIT = QtGui.QLabel(self.tabParam)
        self.TEMP_LOW_LIMIT.setObjectName(_fromUtf8("TEMP_LOW_LIMIT"))
        self.horizontalLayout_13.addWidget(self.TEMP_LOW_LIMIT)
        self.lineEditTEMP_LOW_LIMIT = QtGui.QLineEdit(self.tabParam)
        self.lineEditTEMP_LOW_LIMIT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTEMP_LOW_LIMIT.setObjectName(_fromUtf8("lineEditTEMP_LOW_LIMIT"))
        self.horizontalLayout_13.addWidget(self.lineEditTEMP_LOW_LIMIT)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelVOLT_HIGH_LIMIT = QtGui.QLabel(self.tabParam)
        self.labelVOLT_HIGH_LIMIT.setObjectName(_fromUtf8("labelVOLT_HIGH_LIMIT"))
        self.horizontalLayout_14.addWidget(self.labelVOLT_HIGH_LIMIT)
        self.lineEditVOLT_HIGH_LIMIT = QtGui.QLineEdit(self.tabParam)
        self.lineEditVOLT_HIGH_LIMIT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditVOLT_HIGH_LIMIT.setObjectName(_fromUtf8("lineEditVOLT_HIGH_LIMIT"))
        self.horizontalLayout_14.addWidget(self.lineEditVOLT_HIGH_LIMIT)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.labelVOLT_LOW_LIMIT = QtGui.QLabel(self.tabParam)
        self.labelVOLT_LOW_LIMIT.setObjectName(_fromUtf8("labelVOLT_LOW_LIMIT"))
        self.horizontalLayout_15.addWidget(self.labelVOLT_LOW_LIMIT)
        self.lineEditVOLT_LOW_LIMIT = QtGui.QLineEdit(self.tabParam)
        self.lineEditVOLT_LOW_LIMIT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditVOLT_LOW_LIMIT.setObjectName(_fromUtf8("lineEditVOLT_LOW_LIMIT"))
        self.horizontalLayout_15.addWidget(self.lineEditVOLT_LOW_LIMIT)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.labelDISCHARGE_LIMIT = QtGui.QLabel(self.tabParam)
        self.labelDISCHARGE_LIMIT.setObjectName(_fromUtf8("labelDISCHARGE_LIMIT"))
        self.horizontalLayout_16.addWidget(self.labelDISCHARGE_LIMIT)
        self.lineEditDISCHARGE_LIMIT = QtGui.QLineEdit(self.tabParam)
        self.lineEditDISCHARGE_LIMIT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditDISCHARGE_LIMIT.setObjectName(_fromUtf8("lineEditDISCHARGE_LIMIT"))
        self.horizontalLayout_16.addWidget(self.lineEditDISCHARGE_LIMIT)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.labelCHARGE_LIMIT = QtGui.QLabel(self.tabParam)
        self.labelCHARGE_LIMIT.setObjectName(_fromUtf8("labelCHARGE_LIMIT"))
        self.horizontalLayout_17.addWidget(self.labelCHARGE_LIMIT)
        self.lineEditCHARGE_LIMIT = QtGui.QLineEdit(self.tabParam)
        self.lineEditCHARGE_LIMIT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditCHARGE_LIMIT.setObjectName(_fromUtf8("lineEditCHARGE_LIMIT"))
        self.horizontalLayout_17.addWidget(self.lineEditCHARGE_LIMIT)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.labelVOLT_MSG_RATE = QtGui.QLabel(self.tabParam)
        self.labelVOLT_MSG_RATE.setObjectName(_fromUtf8("labelVOLT_MSG_RATE"))
        self.horizontalLayout_18.addWidget(self.labelVOLT_MSG_RATE)
        self.lineEditVOLT_MSG_RATE = QtGui.QLineEdit(self.tabParam)
        self.lineEditVOLT_MSG_RATE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditVOLT_MSG_RATE.setObjectName(_fromUtf8("lineEditVOLT_MSG_RATE"))
        self.horizontalLayout_18.addWidget(self.lineEditVOLT_MSG_RATE)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.labelTEMP_MSG_RATE = QtGui.QLabel(self.tabParam)
        self.labelTEMP_MSG_RATE.setObjectName(_fromUtf8("labelTEMP_MSG_RATE"))
        self.horizontalLayout_19.addWidget(self.labelTEMP_MSG_RATE)
        self.lineEditTEMP_MSG_RATE = QtGui.QLineEdit(self.tabParam)
        self.lineEditTEMP_MSG_RATE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTEMP_MSG_RATE.setObjectName(_fromUtf8("lineEditTEMP_MSG_RATE"))
        self.horizontalLayout_19.addWidget(self.lineEditTEMP_MSG_RATE)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.labelOCV_MSG_RATE = QtGui.QLabel(self.tabParam)
        self.labelOCV_MSG_RATE.setObjectName(_fromUtf8("labelOCV_MSG_RATE"))
        self.horizontalLayout_20.addWidget(self.labelOCV_MSG_RATE)
        self.lineEditOCV_MSG_RATE = QtGui.QLineEdit(self.tabParam)
        self.lineEditOCV_MSG_RATE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOCV_MSG_RATE.setObjectName(_fromUtf8("lineEditOCV_MSG_RATE"))
        self.horizontalLayout_20.addWidget(self.lineEditOCV_MSG_RATE)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.labelIR_MSG_RATE = QtGui.QLabel(self.tabParam)
        self.labelIR_MSG_RATE.setObjectName(_fromUtf8("labelIR_MSG_RATE"))
        self.horizontalLayout_21.addWidget(self.labelIR_MSG_RATE)
        self.lineEditIR_MSG_RATE = QtGui.QLineEdit(self.tabParam)
        self.lineEditIR_MSG_RATE.setMaximumSize(QtCore.QSize(16777205, 16777215))
        self.lineEditIR_MSG_RATE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditIR_MSG_RATE.setObjectName(_fromUtf8("lineEditIR_MSG_RATE"))
        self.horizontalLayout_21.addWidget(self.lineEditIR_MSG_RATE)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.labelMACRO_MSG_RATE = QtGui.QLabel(self.tabParam)
        self.labelMACRO_MSG_RATE.setObjectName(_fromUtf8("labelMACRO_MSG_RATE"))
        self.horizontalLayout_10.addWidget(self.labelMACRO_MSG_RATE)
        self.lineEditMACRO_MSG_RATE = QtGui.QLineEdit(self.tabParam)
        self.lineEditMACRO_MSG_RATE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditMACRO_MSG_RATE.setObjectName(_fromUtf8("lineEditMACRO_MSG_RATE"))
        self.horizontalLayout_10.addWidget(self.lineEditMACRO_MSG_RATE)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.lineEdit = QtGui.QLineEdit(self.tabParam)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonSet = QtGui.QPushButton(self.tabParam)
        self.pushButtonSet.setObjectName(_fromUtf8("pushButtonSet"))
        self.horizontalLayout_2.addWidget(self.pushButtonSet)
        self.pushButtonGet = QtGui.QPushButton(self.tabParam)
        self.pushButtonGet.setObjectName(_fromUtf8("pushButtonGet"))
        self.horizontalLayout_2.addWidget(self.pushButtonGet)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabParam, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 38))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet(_fromUtf8(""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setStyleSheet(_fromUtf8(""))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelState.setText(_translate("MainWindow", "State: ", None))
        self.pushButtonLog.setText(_translate("MainWindow", "Log", None))
        self.pushButtonDel.setText(_translate("MainWindow", "Delete", None))
        self.pushButtonLive.setText(_translate("MainWindow", "Live", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop", None))
        self.labelCell.setText(_translate("MainWindow", "Cell Data", None))
        self.labelTemp.setText(_translate("MainWindow", "Temperature Data", None))
        self.labelMod.setText(_translate("MainWindow", "Module Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLive), _translate("MainWindow", "Live", None))
        self.labelOcv.setText(_translate("MainWindow", "Open Circuit Voltage", None))
        self.labelOhm.setText(_translate("MainWindow", "Internal Resistance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCellinfo), _translate("MainWindow", "Cell Info", None))
        self.labelCAN.setText(_translate("MainWindow", "CAN Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCAN), _translate("MainWindow", "CAN", None))
        self.checkBoxCellVolt.setText(_translate("MainWindow", "Cell Voltage", None))
        self.checkBoxCellTemp.setText(_translate("MainWindow", "Cell Temperature", None))
        self.checkBoxPackVol.setText(_translate("MainWindow", "Pack Voltage", None))
        self.checkBoxPackCur.setText(_translate("MainWindow", "Pack Current", None))
        self.checkBoxMod.setText(_translate("MainWindow", "Module Information", None))
        self.labelTEMP_HIGH_LIMIT.setText(_translate("MainWindow", "TEMP_HIGH_LIMIT", None))
        self.TEMP_LOW_LIMIT.setText(_translate("MainWindow", "TEMP_LOW_LIMIT", None))
        self.labelVOLT_HIGH_LIMIT.setText(_translate("MainWindow", "VOLT_HIGH_LIMIT", None))
        self.labelVOLT_LOW_LIMIT.setText(_translate("MainWindow", "VOLT_LOW_LIMIT", None))
        self.labelDISCHARGE_LIMIT.setText(_translate("MainWindow", "DISCHARGE_LIMIT", None))
        self.labelCHARGE_LIMIT.setText(_translate("MainWindow", "CHARGE_LIMIT", None))
        self.labelVOLT_MSG_RATE.setText(_translate("MainWindow", "VOLT_MSG_RATE", None))
        self.labelTEMP_MSG_RATE.setText(_translate("MainWindow", "TEMP_MSG_RATE", None))
        self.labelOCV_MSG_RATE.setText(_translate("MainWindow", "OCV_MSG_RATE", None))
        self.labelIR_MSG_RATE.setText(_translate("MainWindow", "IR_MSG_RATE", None))
        self.labelMACRO_MSG_RATE.setText(_translate("MainWindow", "MACRO_MSG_RATE", None))
        self.pushButtonSet.setText(_translate("MainWindow", "Set", None))
        self.pushButtonGet.setText(_translate("MainWindow", "Get", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParam), _translate("MainWindow", "Parameters", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

